### ISSUE TITLE
Update SVex to use [tsv6] instead of [tsv7] for [tsv] reposting of archived threads

### ISSUE THREAD

**Issue by Kirzi** [YaManicKill/pokemontrades#2]
[tsv] threads need to be reposted as [tsv6].

It'll also have to be able to recognize [tsv7] threads and repost those as [tsv7] threads for when those start to become archived.

**Comment by SnowPhoenix** [comment]
Made commit f6090fc02c3850dc59570bc48d7065a76143f9fb, which updates the script to replace [tsv] with [tsv6] in content prepared for reposting. A basic check has also been added to reduce the likelihood of affecting links titled "tsv".

[tsv7] should be fine since the existing search query returns those as well, and [tsv7] does not match the regex used for updating the old [tsv] tag.
